#!/usr/bin/env bash
set -e
[ -n "$GD_DEBUG" ] && set -x

# Various documentation of commands.

case "$1" in
"")
echo "usage: git data [command]

git data stores files that are too big to handle in git on remote servers.
Think of it as a very simple git annex.

Commands
  add   store data to s3 or a fileserver you have access to
  sync  download and synchronize the data from the remote servers

Use 'git help [command]' to read more about each command.
"
;;
add)
echo "usage: git data add [file]

Stage a big file, or collection of files if [file] is a glob.

Arguments
  file  the file(s) to be stored.
"
;;
sync)
echo "usage: git data sync <name>

Retrieve each file stored on the remote and restore it in the current directory.

Arguments
  name  (optional) the name in .git/config of the server to store the data
"
;;
*)
echo "unknown command try git data help"
esac
