#!/usr/bin/env bash
. gitdata-functions

tmp=$(tmpfile)
cat >> $tmp

if [ "$(head -c 8 $tmp)" != 'git-data' ]
then
  sha=$(shasum $tmp | cut -f 1 -d ' ' -)
  mv $tmp $(object_dir)/$sha
  echo -e "git-data\t$sha"
else
  cat $tmp
  rm $tmp
fi