#!/usr/bin/env bash
. gitdata-functions

mkdir -p $(object_dir)
git config filter.data.clean  "git-data filter-clean"
git config filter.data.smudge "git-data filter-smudge"
git config filter.data.required 'true'
touch $(attributes)
