#!/usr/bin/env bash
. gitdata-functions

if [ "$(head -c 8 $path)" != 'git-data' ]
then
  tmp=$(tmpfile)
  cat >> $tmp
  sha=$(shasum $tmp | cut -f 1 -d ' ' -)
  mv $tmp $(object_dir)/$sha
  echo -e "git-data\t$sha"
else
  cat
fi