#!/usr/bin/env bash
. gitdata-functions

tmp=$(tmpfile)
cat > $tmp

if [ "$(head -c 8 $tmp)" != 'git-data' ]
then
  gzip $tmp
  sha=$(git hash-object $tmp --no-filters)
  mv $tmp.gz $(object_dir)/$sha
  rm $tmp
  rm $tmp.gz
  echo -e "git-data\t$sha"
else
  cat $tmp
  rm $tmp
fi
