#!/usr/bin/env bash
. gitdata-functions

read file

# nothing we can do if it ain't a git data file
if [ "$(echo $file | head -c 8)" != 'git-data' ]
then
  echo $file
  exit
fi

sha=$(echo -e "$file" | cut -f2 -)
if [ -z $(get_remote) ]
then
  exit 1
else
  get $sha
fi
