#!/usr/bin/env bash

tarball=$(mktemp git-data.tar.gz.XXXXXXXXX)
git_data="`pwd`/.git-data"

get_remote() {
  local key=$1

  if [ -z $key ]
  then
    remote=$(git config --get git-data.origin.url)
  else
    remote=$(git config --get git-data.$key.url)
  fi

  if [ -z $remote ]
  then
    echo "you need to set at least one remote in git-data try: git data remote origin [server]"
    exit 1
  fi
  echo "$remote"
}

set_remote() {
  `git config git-data.$1.server $2`
}

file_name() {
  local sha=$1
  echo "git-data-$sha.tar.gz"
}

# http://docs.amazonwebservices.com/AmazonS3/latest/dev/RESTAuthentication.html
sign_request() {
  local sign=$1
  if [ -z $AWS_SECRET_ACCESS_KEY ] && [ -z $AWS_ACCESS_KEY_ID ]
  then
    echo "You must set AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID to use s3 as an endpoint."
    exit 1
  fi
  echo "$( echo -en $sign | openssl dgst -sha1 -binary -hmac $AWS_SECRET_ACCESS_KEY  | openssl base64 )"
}

http_date() {
  echo $(LC_TIME=C TZ=utc date "+%a, %d %h %Y %T %z")
}


